immunant/IA2-Phase2

header-rewriter/HeaderRewriter.cpp
The error printed seems to imply that we can support returning function
pointers that are a typedef, but we didn't actually check for that case.
=> Make typedef'd function pointer return types work

CMakeLists.txt, cmake/common-wrappers.cmake, cmake/define-ia2-wrapper.cmake, header-rewriter/tests/CMakeLists.txt, header-rewriter/tests/ffmpeg/CMakeLists.txt
Moves the ffmpeg wrapper definitions out of the ffmpeg test and into a
common area for use by other binaries in tree.
This also now includes all available and compilable headers under the ffmpeg
include directories when making a wrapper for these libraries. This
avoids the need to explicitly list headers, while still skipping headers
that simply don't work in the current environment (e.g. missing cuda).
=> Common ffmpeg wrappers

docs/usage.md, header-rewriter/HeaderRewriter.cpp
If we only build against the wrapped headers, without the originals, but
still need to use a variadic function, we need to preserve these
functions in the header. Until #18 is fixed we should still allow users
to call variadics from their current compartment, when possible.
=> Do not remove variadic functions from the wrapped headers

CMakeLists.txt, cmake/common-wrappers.cmake, cmake/define-ia2-wrapper.cmake, header-rewriter/tests/CMakeLists.txt, header-rewriter/tests/ffmpeg/CMakeLists.txt
Moves the ffmpeg wrapper definitions out of the ffmpeg test and into a
common area for use by other binaries in tree.
=> Move common wrappers to their own cmake file 

cmake/define-ia2-wrapper.cmake, cmake/define-test.cmake
ia2.h requires defining _GNU_SOURCE since it uses the definition of
`dl_phdr_info`. Using `#define _GNU_SOURCE` is unreliable since link.h defines
dl_phdr_info and may be included by another header before ia2.h so we have to
use `-D_GNU_SOURCE`.
=> Define _GNU_SOURCE for tests

libia2/ia2.c, libia2/include/ia2.h, libia2/padding.ld
Clean up the protect_pages callback for `dl_iterate_phdr`.
Also relaxes the requirement that `ia2_shared_*` must exist, which lets us fix the linker script to eliminate these sections if they aren't required.
=> Refactor and clean up `protect_pages()` and fix alignment requirements

header-rewriter/GenCallAsm.cpp, header-rewriter/GenCallAsm.h, header-rewriter/HeaderRewriter.cpp
The source rewriter prototype in PR #177 required refactoring GenCallAsm.cpp so I'm splitting out those changes to make review easier.
A `caller_pkey` argument is useful since the rewriter will eventually read all source files and know which compartment all functions. This means it'll be able to insert the caller and target pkeys itself instead of relying on the "compile with -DCALLER_PKEY" hack.
=> Refactor GenCallAsm.cpp

header-rewriter/GenCallAsm.cpp, header-rewriter/GenCallAsm.h, header-rewriter/HeaderRewriter.cpp
The three calls to `emit_asm_wrapper` generate three different types of wrappers. It accepts a `WrapperKind` enum with two variants which we used in combination with the presecence of an explicit `as_macro` argument to determine which of the three types of wrappers to generate. This commit adds an explicit 3rd `WrapperKind` variant and fixes the logic that relies on `as_macro` to use just the `WrapperKind` instead. The only thing that `as_macro` affects now is the terminator used when writing each line of asm.
This is part of the refactoring from PR #177 and the last one for now.
=> Add explicit third variant to WrapperKind enum in GenCallAsm.cpp

libia2/include/test_fault_handler.h
`_exit` skips `atexit` routines and dtors, which is good because we do not want to possibly segfault (and wrongly print a happy message) during execution of other code that only ran because we called `exit()` inside the `CHECK_VIOLATION` handler; once we get to this point of `CHECK_VIOLATION`, we want to end the test immediately.
=> use `_exit` in `CHECK_VIOLATION`

header-rewriter/GenCallAsm.cpp
Adding symbol type and size suppresses the ld warning "type and size of dynamic symbol `wrapper_name` are not defined"
=> Create a local symbol for static wrappers and add symbol type/size

libia2/CMakeLists.txt, libia2/ia2.c, libia2/include/ia2.h, libia2/main.c, libia2/threads.c
This means writing the PKRU before `main` and switching stacks for both `main` and thread body functions.
We do not currently restore PKRU after calling `main`; that's what @rinon is working on.
This PR also includes some security fixes around threading setup and TLS; see the commits "move thread-local padding to ia2.h and verify untrusted compartment TLS padding at runtime" and "fix stack/tls setup logic".
Fixes #171.
=> Switch compartments for main function and thread body functions

header-rewriter/SourceRewriter.cpp, header-rewriter/tests/rewrite_fn_ptr_eq/main.c
This adds two new AST matchers to the FnPtrEq rewriter pass for when functions appear on either side of a binary operator (excluding assignments). These passes rewrite function operands as `IA2_FN_ADDR(function)` which expands to the address of the call gate wrapper for the function. This is necessary because if the other side of the binary operator is a function pointer it can only ever be NULL or point to a call gate wrapper so it can never be equal to the original function. Also while the existing FnPtrEq matchers applied to all non-assignment binary operators (e.g. `some_condition && ptr` or ||), the changes above only apply to the == and != operators.
The first commit also restricts the cases that the FnPtrExpr pass applies to to avoid overlap with the new AST matchers. This is …
=> Rewrite functions compared to function pointers

header-rewriter/SourceRewriter.cpp, header-rewriter/tests/read_config/main.c, header-rewriter/tests/simple1/main.c, header-rewriter/tests/trusted_indirect/main.c
Since all translation units must be compiled with `-DPKEY=N` we can use this macro to avoid specifying the pkey argument in the IA2_CALL macro. This commit also updates tests with `IA2_CALL` and enables the rewriter checks in the read_config and trusted_indirect tests.
=> Remove PKEY argument from IA2_CALL macro

rewriter/SourceRewriter.cpp, rewriter/tests/read_config/main.c, rewriter/tests/simple1/main.c, rewriter/tests/trusted_indirect/main.c
Marked as WIP since I'm not sure if we want to merge this yet and because this doesn't completely remove the mangled type IDs. Ideally we'd remove them completely and leave only the mangled types in symbol names (i.e. won't be visible to the user) to simplify #208.
=> Remove mangled type ID from IA2_CALL macro

rewriter/SourceRewriter.cpp, rewriter/tests/read_config/main.c, rewriter/tests/simple1/main.c, rewriter/tests/trusted_indirect/main.c
This reverts the commits in #222 because they require declaring all types which appear as arguments/return values in function pointer types in the generated header. Since some types such as typedefs and enums cannot be forward declared, this requires moving around existing type definitions which is tricky because of dependencies among types.
=> Revert "Remove mangled type ID from IA2_CALL macro"

libia2/include/permissive_mode.h
Permissive mode installs a signal handler that switches the PKRU for a single instruction on segfaults then switches it back after redoing the memory access. To use it just `#include` the new header. See the header documentation for details.
=> Add permissive mode header

rewriter/SourceRewriter.cpp
Jumping to a separate abort label hid the location that actually asserted when using a debugger. This change moves the abort instruction into the assert itself instead so that we abort with a useful PC value.
=> Simplify ASSERT_PKRU to abort inline

CMakeLists.txt, libia2/CMakeLists.txt, libia2/include/ia2.h, libia2/include/permissive_mode.h, libia2/test/CMakeLists.txt, libia2/test/permissive_mode.c
Permissive mode had a few issues, most importantly:
- PKRU offset cpuid call was using the wrong register
- PKRU was not modified properly if it was 0 before the signal handler
The kernel only restores the PKRU value from the XSAVE area after the
signal handler if the PKRU bit in the XSAVE header is set (See Intel
manual Chapter 13.4 and linux kernel xstate.c). We want to change the
PKRU value after the permissive mode handler runs, so we need to make
sure this header bit is unconditionally set. If the PKRU value was 0,
the kernel will not set the bit before the signal handler runs.
Fixes #238
=> Fix permissive mode to restore PKRU

libia2/include/ia2.h, libia2/include/permissive_mode.h
Suppress warnings on potentially unused variables and labels, and fix a couple type mismatch warnings.
=> Fix warnings

cmake/define-test.cmake, libia2/CMakeLists.txt, libia2/test/CMakeLists.txt
Binaries that use libia2 should pick up defines from the library module, rather than having to re-declare the same defines every time we use the library. Moves the LIBIA2_INSECURE and LIBIA2_DEBUG definitions to libia2 itself.
=> Move defines to libia2 cmake module

external/chromium/src/base/allocator/partition_allocator/partition_bucket.cc, libia2/CMakeLists.txt, libia2/ia2.c, libia2/include/ia2.h, libia2/include/ia2_compartment_init.inc, partition-alloc/CMakeLists.txt, partition-alloc/src/allocator_shim.cc, scripts/partition_alloc/partition_alloc.diff
Secure global data pkey_mprotect calls by ensuring that we can access
the pages that we are switching to our private compartment. We do this
by switching to the compartment target, verifying that the expected
target compartment and current pkey matches, then attempting to read
from each page in the protection range before protecting the pages as
private to the target compartment.
Fixes #172
=>  Switch to compartment and probe global data pages during init

libia2/include/ia2.h
This macro was accidentally restored after rebasing on top of #254. Removes that macro again.
=> Remove leftover definition of INIT_COMPARTMENT macro

libia2/ia2.c, libia2/include/ia2.h, libia2/include/ia2_internal.h, libia2/include/permissive_mode.h, rewriter/SourceRewriter.cpp
Adds ia2_internal.h for internal implementation definitions that users don't need to see. Refactors everything internal into this header and combines macro definitions.
Fixes #160
=> Refactor ia2.h into public and private headers

libia2/include/permissive_mode.h
- Improves logging in permissive mode to print offsets rather than absolute addresses when possible.
- Abort on segfaults that are not PKRU violations in permissive mode.
=> Permissive mode improvements

external/nginx/auto/cc/gcc, external/nginx/src/core/ngx_array.h, external/nginx/src/core/ngx_hash.h, external/nginx/src/core/ngx_rbtree.h, external/nginx/src/core/ngx_string.h, external/nginx/src/os/unix/ngx_alloc.h, external/nginx/src/os/unix/ngx_files.h, external/nginx/src/os/unix/ngx_time.h, libia2/include/ia2.h, rewriter/SourceRewriter.cpp
Some functions, e.g. utility functions that don't touch global state,
should not be wrapped and should always run in the caller compartment.
If we wrap these functions they may act as simple accessors for another
compartment's private data. For example, consider an vector_pop()
function that pops an element from a vector. If this function is
declared in compartment A and used from compartment B, it allows
compartment B to pop any element from compartment A's private vectors.
This change adds the `ia2_skip_wrap` annotation attribute that skips
wrapping of any functions, and function pointers it is applied to (and
calls to these function pointers). It should be applied with the
following set of pragmas:
#pragma clang attribute push (__attribute__((annotate("ia2_skip_wrap"))), apply_to = …
=> rewriter: Add clang attribute to skip wrapping functions

libia2/threads.c, rewriter/tests/heap_two_keys/main.c, rewriter/tests/permissive_mode/permissive_mode.c, rewriter/tests/read_config/plugin.c
Should be non-contentious, PR for CI. I think recent ia2.h and permissive_mode.h cleanups mean our headers no longer provide these so consumers need them separately.
=> Add some missing #includes

rewriter/SourceRewriter.cpp
This improves diagnostics when running the rewriter on a set of source files that has `-DPKEY=N` but omitted `#include <ia2_compartment_init.inc>` by mistake. Previously this just caused the `fn_decl_pass.abi_signatures.at(fn_name)` to fail, aborting the program with no clear indication of the issue.
=> rewriter: Improve error message when missing compartment_init.inc

rewriter/GenCallAsm.cpp
If a call gate's caller has pkey zero then its memory is accessible to all compartments and we shouldn't care about scrubbing registers before calling the target since its memory is not protected anyway. If the call gate's target has pkey zero then the same argument holds for the register scrubbing after calling the target function.
=> rewriter: Omit register scrubbing when caller/target pkey are zero

libia2/CMakeLists.txt, libia2/exit.c, rewriter/tests/CMakeLists.txt, rewriter/tests/destructors/CMakeLists.txt, rewriter/tests/destructors/include/main/exported_fn.h, rewriter/tests/destructors/include/plugin/plugin.h, rewriter/tests/destructors/main.c, rewriter/tests/destructors/plugin.c, rewriter/tests/lit.cfg.py
Destructors are wrapped to run in their respective compartments, but transition back to compartment 0 after running. This means that the caller stack must be writable in compartment 0. This change wraps exit(3) and transitions to compartment 0 and the shared stack before running exit() from libc.
Fixes #285
=> Switch to compartment 0 when calling exit(3)

rewriter/tests/lit.cfg.py, rewriter/tests/minimal/main.c, rewriter/tests/permissive_mode/permissive_mode.c, rewriter/tests/read_config/main.c, rewriter/tests/read_config/plugin.c, rewriter/tests/sighandler/main.c, rewriter/tests/tls_protected/library.c, rewriter/tests/tls_protected/main.c, rewriter/tests/two_keys_minimal/main.c, rewriter/tests/two_keys_minimal/plugin.c, rewriter/tests/two_shared_ranges/main.c, rewriter/tests/two_shared_ranges/plugin.c
Make lit opt-in rather than opt-out, and remove segment checks.
=> Make lit optional

libia2/include/permissive_mode.h
The values that cause MPK errors in the permissive mode logs are assumed to be uint64_t, but they may be any type. Since we don't always have reliable runtime type info or a reasonable way to determine the size of the memory access from the sighandler (I don't want to parse x86 instructions if possible), we arbitrarily assume that they're u64 and access them as such. This is a problem if the address is not aligned to 8 bytes so this commit replaces the direct pointer access with a memcpy to avoid the alignment requirement.
=> libia2: Fix alignment issue in permissive mode

libia2/include/ia2_internal.h, runtime/memory-map/src/lib.rs, runtime/memory_map.h, runtime/track_memory_map.c
This lets us avoid errors when running programs with destructors under the memory-map tracking runtime.
I want to factor out the magic constant--where should it live?
=> Mark the end of IA2 init

runtime/forbid_paths.c, runtime/get_inferior_pkru.c, runtime/memory-map/src/lib.rs, runtime/memory_map.h, runtime/mmap_event.c, runtime/mmap_event.h, runtime/seccomp_filter.c, runtime/track_memory_map.c
`madvise(MADV_DONTNEED)` is equivalent to zeroing memory; we cannot allow this to be performed cross-compartment.
Because some other 'advices' may also have similar effects, for now we simply forbid all cross-compartment `madvise(advice)` calls regardless of the value of `advice`. We can loosen this policy if needed by some applications down the line, but for now this patches the security hole while keeping our tests passing.
This took a few iterations to get tests green again. Round-by-round:
1. The first commit failed tests for a couple reasons, the primary of which is that the `madvise()` policy was being tripped and forbidding a `madvise(MADV_DONTNEED)` inside `free()` in PartitionAlloc. To debug this, I added the next few commits, through `runtime/track_memory_map: print details of …
=> Trace `madvise` syscall

runtime/tracer/forbid_paths.c
This is the fix I added in #311 for a procfs issue. On second thought the cleaner solution would be to propagate actual errors from allow_path to its callers and check those like we did in #318 with ENOENT.
=> runtime/tracer: Ignore procfs race in syscall tracer

tests/read_config/main.c, tests/rewrite_macros/include/lib.h, tests/rewrite_macros/main.c, tests/simple1/main.c, tests/trusted_indirect/main.c, tools/rewriter/SourceRewriter.cpp
Closes #326. Also the nginx demo doesn't need to be updated since no IA2_CALL macros were added checked in.
=> tools/rewriter: Replace type IDs with mangled types again

cmake/ia2.cmake, runtime/libia2/CMakeLists.txt, tools/pad-tls/pad-tls.c
Previously CMake was picking up libc.so for x86 and running pad-tls on that. We were seemingly linking against it but the basic ARM test wasn't failing since QEMU doesn't actually load the guest libc.so into the address space only ld.so. This fixes both libc lookup paths and modifies pad-tls to allow EM_AARCH64. Since this has no effect on the ARM test when emulating with QEMU I checked the libc copy in the build dir manually.
=> pad-tls: Add support for ARM64 to pad-tls and fix libc lookup in CMake

tools/rewriter/GenCallAsm.cpp, tools/rewriter/SourceRewriter.cpp
Merge in my branch with the no-op call gates and call gates refactoring for multi-arch.
WIP, still working on making sure this is the correct assembly, but the `minimal_arm_main_wrapped` target compiles.
=> Generate no-op call gates for ARM64

.github/workflows/ci.yml, CMakeLists.txt, cmake/ia2.cmake, docs/directory_structure.md, misc/CMakeLists.txt, misc/spoofed_criterion/CMakeLists.txt, misc/spoofed_criterion/include/criterion/criterion.h, misc/spoofed_criterion/include/criterion/logging.h, misc/spoofed_criterion/include/criterion/new/assert.h, misc/spoofed_criterion/test_runner.c
I got criterion working with ARM/QEMU in CI on #335 but objdump shows that libcriterion.so clobbers x18. Instead of building it and all transitive deps with ffixed-x18 let's just spoof criterion for now. This unblocks a lot of the small tasks in #314 which depend on libs not clobbering x18.
This lets us build all tests (modulo x86 code we haven't ifdefed out in libia2) but there's no cmake command to build all tests, only build and test w/o QEMU. We should either add a target to build all tests or add support for testing with QEMU.
=> misc: spoof criterion for ARM

tools/rewriter/DetermineAbi.cpp, tools/rewriter/DetermineAbi.h, tools/rewriter/GenCallAsm.h, tools/rewriter/SourceRewriter.cpp
Add some comments in determineABI as I work through supporting ARM. There are several question points I've marked with TODO.
Regarding `determineAbi`, On aarch64, section 6.9 of the ABI writes:
>If the type, T, of the result of a function is such that `void func(T arg)` would require that arg be passed as a value in a register (or set of registers) according to the rules in Parameter passing, then the result is returned in the same registers as would be used for such an argument.
This is a little confusing but basically means return types are returned according to the same rules as for parameters, if I'm understanding this correctly. Composite (ie struct) arguments larger than 16 bytes (two registers) must go on the stack, so we still have the same two-register limitation as on x86.
Some …
=> Initial determineAbi work for ARM

.github/workflows/ci.yml
Close #339.
Non-tracing-enabled runs will now continue but the overall run will still fail if a tracing-enabled one does. LMK if this is the desired functionality or not.
=> Don't fail fast if tracing-enabled tests fail

runtime/tracer/forbid_paths.c
This is the only case that was silent previously. Follow-up to #330.
=> runtime/tracer: print error when fstat fails

runtime/libia2/include/ia2_internal.h
This is a weird thing around #include order when we run the rewriter. Tiny fix but I had already spent the time tracking it down so here it is. PR mostly just for CI.
=> ia2_internal.h: avoid dl_phdr_info warning

misc/spoofed_criterion/CMakeLists.txt, misc/spoofed_criterion/include/criterion/criterion.h, misc/spoofed_criterion/test_runner.c, tests/CMakeLists.txt
This does not handle forking correctly so we need to combine it with #343
=> spoofed_criterion: Support non-zero exit code and enable should_segafult test on ARM

external/chromium/src/base/allocator/partition_allocator/partition_alloc_base/compiler_specific.h
This makes it easier to peruse our CI output.
=> partition-alloc: fix warnings in CI

runtime/libia2/include/ia2_internal.h, tests/CMakeLists.txt
The sighandler test now builds and runs. It fails at a `CHECK_VIOLATION` (as expected) because MTE is not enabled. I don't think it makes much sense to enable MTE before adding in real call gates (we currently just jump to the target function) so this and the tests in the other PRs should get enabled after #333 lands.
=> libia2: Allow defining compartment-aware signal handlers on ARM and re-enable test

.github/workflows/ci.yml
this only saves us about a minute of CI time, but I'd rather debug our first CI caching against a 1-minute QEMU build than Clang's interminable build
=> ci: cache built QEMU

.github/workflows/ci.yml
rav1d does this and it seems like a good idea; maybe it'll shave a few more seconds off of CI
=> ci: cache apt packages

.github/workflows/ci.yml
First some `ci.yml` tweaks to QEMU that we'll want for Clang, then the Clang build itself.
=> ci: build+cache Clang

docs/build_instructions.md
Add a missing '=' character that caused the cmake instructions to not work.
=> Fix typo in cmake instructions

tools/rewriter/SourceRewriter.cpp
=> rewriter: fix infinite loop by adding an `llvm::cl::parser` requiring directory args to exist

tools/rewriter/SourceRewriter.cpp
* Fixes #367.
This fixes #367 in that the files are no longer truncated, but a clearer error message is printed instead.  This doesn't fix the root cause of #367, which probably has more to do with #368 and the `compile_commands.json` not getting read correctly, but it does fix the alarming behavior of deleting the contents of a ton of files.
=> rewriter: skip copying files if the output file is the same file to avoid truncating them

runtime/libia2/include/ia2_internal.h
It's more convenient if successful builds don't print that word. These are just verbose TODOs anyhow.
=> ia2: avoid "error" in #warning

.github/workflows/ci.yml
Running out of disk space to create the cache archive may be why our caching is not working.
=> ci: try freeing space up by deleting LLVM libs after building Clang

misc/spoofed_criterion/include/criterion/criterion.h, misc/spoofed_criterion/include/criterion/logging.h, misc/spoofed_criterion/include/criterion/new/assert.h, misc/spoofed_criterion/test_runner.c
Fixes some failing tests, not-building tests, ~and spuriously passing tests~ on AArch64. The tests depend on other work in addition to these fixes before they'll actually pass on AArch64, but this fills in missing testing infrastructure.
EDIT: I've split the `test_fault_handler` changes into a separate PR (#378) because they uncover brokenness that we need to fix separately while most of this infrastructure is strictly additive and needed to run more AArch64 tests.
=> Flesh out `spoofed_criterion` for AArch64

tools/rewriter/SourceRewriter.cpp
Also, ignore existing directories when copying files.
Also, do the skipping if the file is the same before anything else (like creating the directories, or marking the file as copied).
=> rewriter: use `llvm::sys::fs::create_directories` instead of doing the logic ourselves

tools/rewriter/SourceRewriter.cpp
Add an error message in the case where pkeys are setup incorrectly so that users can more easily debug their pkey setup.
=> Improve error for invalid pkey range

tools/rewriter/DetermineAbi.cpp
* Fixes #390.
This doesn't actually handle the type, but it avoids segfaulting and dumps the unexpected type. In this case, it happens to be a `union`, which we need to handle I believe, but we can do that in a follow-up PR.
=> rewriter: avoid segfaulting on non-scalar, non-struct direct types

.github/workflows/ci.yml
I noticed CI wasn't running on stacked PRs, so this runs CI on all PRs so that stacked PRs work.  I'm not sure if there was a reason for only running CI on PRs into `main`, but I'd prefer if we changed it.
=> ci: run CI on all PRs, not just PRs to `main`, so we can stack PRs

cmake/ia2.cmake, runtime/libia2/CMakeLists.txt, runtime/libia2/exit.c, runtime/libia2/ia2.c, runtime/libia2/include/ia2_compartment_init.inc, runtime/libia2/include/ia2_internal.h, runtime/libia2/include/scrub_registers.h, runtime/libia2/include/test_fault_handler.h, runtime/libia2/init.c, runtime/libia2/main.c, runtime/libia2/threads.c, runtime/partition-alloc/CMakeLists.txt
After seeing @randomPoison run into this same issue that I ran into as well, and since @fw-immunant said we probably don't need our own `LIBIA2_{X86_64,AARCH64}` macros and can use the builtin `__{x86_64,aarch64}__` macros, I thought it'd be simpler to fix this here in ia2 vs. handle defining them in the correct places in `dav1d`'s `meson.build`s.
`dav1d` also uses `-Wundef`, so `#if`/`#elif`s directly on `__{x86_64,aarch64}__` warn about being undefined on the other architecture, so I changed them all to `#if`/`#elif` `define(...)`.  I could use `#ifdef ...` and then `#elif defined(...)`, but for consistency between the two, I just stuck to using `defined` in both places.
=> runtime: use builtin `__{x86_64, aarch64}__` instead of `LIBIA2_{X86_64,AARCH64}`

tools/rewriter/SourceRewriter.cpp
* Fixes #393.
We discussed this separately, and besides just cases like `dav1d` where this is done for templating reasons, this is also done in other places, I think for static and dynamic libraries maybe?  Given that, it's simpler to just use the first compile command and emit a warning about it.  We already emit warnings on other things that might be an issue (e.x. unsupported variadic function pointers), so I think this is okay.
=> rewriter: warn on multiple compile commands per src and truncate to first one

tools/rewriter/SourceRewriter.cpp
* Fixes #393.
We discussed this separately, and besides just cases like `dav1d` where this is done for templating reasons, this is also done in other places, I think for static and dynamic libraries maybe?  Given that, it's simpler to just use the first compile command and emit a warning about it.  We already emit warnings on other things that might be an issue (e.x. unsupported variadic function pointers), so I think this is okay.
I accidentally merged #398 into a non-`main` branch.  This PR is into `main` directly, and I'll merge it right away since #398 was already approved.
=> rewriter: warn on multiple compile commands per src and truncate to first one (reopened #398)

runtime/libia2/include/test_fault_handler.h, tests/CMakeLists.txt, tests/lit.cfg.py
We previously tested for the printed message with FileCheck, but now our Criterion-based tests only care about exit codes.
This was hiding test failures on both AArch64 and x86_64.
Based on bisecting it appears the `three_keys_minimal` test has never worked but its failures have always been masked by the `test_fault_handler` bug that this fixes. I'll look into things more tomorrow.
=> test_fault_handler: exit nonzero if expected segfault missing

cmake/ia2.cmake, tests/CMakeLists.txt, tests/lit.cfg.py
The partition-alloc module exported public linker options, but this was not propagated through the padded version of the library. This change propagates PUBLIC LINK_OPTIONS from partition-alloc to its consumers.
=> Fix propagation of partition-alloc link options

runtime/libia2/ia2.c, tests/CMakeLists.txt
ELF segment end computation was using the page-aligned start, not the virtual address start (which may not be page-aligned). This was resulting in not protecting the BSS section.
=> Fix ELF segment end computation

tools/rewriter/CAbi.h, tools/rewriter/DetermineAbi.cpp, tools/rewriter/GenCallAsm.cpp
Clang started packing structs immediately after
stack arguments, but we used to copy memory
arguments as 8-byte chunks. Instead, copy only up
to the size of the struct argument to avoid
overwriting other bytes above it on the stack.
Fixes #365
=> Fix struct copying for structs with an unaligned size

runtime/libia2/include/ia2_compartment_init.inc, runtime/libia2/include/permissive_mode.h
Projects being rewritten and compiled may have warnings/errors like this turned on, so it's simpler to just fix them.
Note that this doesn't set `-Werror=sign-compare` in `cmake` because that'll apply to all of the tests, too.  We just want to make sure that included headers work under different possible warning/error configurations a project might set.
=> runtime: fix `-Wsign-compare` warnings

runtime/libia2/include/ia2_internal.h, runtime/libia2/init.c
`_Noreturn` doesn't exist before C11, and is deprecated in C23 (in favor or `[[noreturn]]`), so it's simpler just to use `__attribute__((__noreturn__))` since we don't know what C version the headers will be compiled with.
=> runtime: use `__attribute__((__noreturn__))` instead of `_Noreturn` to avoid errors

runtime/libia2/include/ia2_compartment_init.inc, runtime/libia2/include/ia2_internal.h, runtime/libia2/threads.c
* Fixes #442.
Making the visibility explicit for these allows projects to be compiled with `-fvisibility=hidden`, which sets the default (not `default`) to `hidden`.
=> runtime: mark runtime functions used by other TUs as `__attribute__((visibility("default")))`

runtime/libia2/include/ia2_compartment_init.inc, runtime/libia2/include/ia2_internal.h, runtime/libia2/main.c
Rather than saving and restoring the PKRU from a register when allocating and securing thread stacks, we branch on the initial value to one of a set of duplicated initialization routines, each of which hard-codes the PKRU value to restore after initialization.
Fixes #257
=> Secure PKRU during thread startup

tests/CMakeLists.txt, tests/static_addr_taken/CMakeLists.txt, tests/static_addr_taken/include/static_fns.h, tests/static_addr_taken/lib.c, tests/static_addr_taken/main.c, tools/rewriter/SourceRewriter.cpp
Handles adding `used` attribute to functions defined in headers or that begin with a macro expansion.
=> Improve static address taken function rewriting

runtime/libia2/include/ia2_internal.h, runtime/libia2/init.c, runtime/libia2/main.c
~We weren't tagging the entire requested region but only its first page (which also impacted protection of non-stack pages).~ (Fixed separately.)
After allocating and tagging a fresh compartment stack, we returned an untagged pointer to it, which led to MTE violations. I was surprised by this because the violations I observed seemed to come from `sp`-relative accesses, which I thought would not perform MTE checks, but they did anyway--it would be good to write a test program to characterize exactly which instructions do and don't perform MTE checks.
In addition, we need to apply tags for the access to TLS when accessing `ia2_stackptr_N`.
=> Fix stack tagging on AArch64

runtime/libia2/include/ia2.h, runtime/libia2/include/ia2_internal.h, tests/abi/include/abi.h, tests/abi/main.c, tests/read_config/main.c, tests/rewrite_macros/include/lib.h, tests/rewrite_macros/main.c, tests/simple1/main.c, tests/trusted_indirect/main.c, tools/rewriter/GenCallAsm.cpp, tools/rewriter/GenCallAsm.h, tools/rewriter/SourceRewriter.cpp
Rather than pass the indirect call target in a global static, this change passes the target in the first parameter register to the wrapper. The wrapper then shifts the remaining parameters so that the callee receives the correct parameters.
=> Pass indirect call target in first register

tools/rewriter/GenCallAsm.cpp, tools/rewriter/GenCallAsm.h, tools/rewriter/SourceRewriter.cpp
We previously defined call gates for pointers to static functions by appending a macro to the rewritten source files. In that case we had to do this because the static function may not be referenced from outside the translation unit. For pointers to globally-visible functions we defined the call gates in the call gate .so for simplicity. This commit changes the latter call gates so they're defined like the former. This change simplifies control-flow since the call gate no longer requires cross-DSO calls and makes it possible to support programs that are intended to be compiled with -fvisibility=hidden since functions that may have hidden visibility are only referenced by call gates within the DSO that defines them. Partially addresses #435.
=> rewriter: Define call gates for function pointers in source defining the pointee

runtime/libia2/include/ia2_internal.h, runtime/libia2/init.c
`allocate_stack_0` writes the allocated stack to `ia2_stackptr_0`. Previously, this was done inline in `init_stacks_and_setup_tls`, which is defined in the main compartment with `INIT_RUNTIME`, and thus may sometimes use the "Local Exec" TLS model and thus use a different thread-local address. Moving this to `allocate_stack_0` in `libia2` forces it to use the correct GOT thread local.
This is a workaround to #457, but doesn't actually fix the root issue, so I'm not sure if we should merge it instead of fixing #457 properly. But it does successfully prevent compartmentalized `dav1d` from segfaulting, and thus is included in #454.
=> runtime: extract out `allocate_stack_0` to work around a "Local Exec" TLS model issue and prevent segfaulting

misc/test_runner/include/ia2_test_runner.h, misc/test_runner/test_runner.c
* Fixes #473.
The previous way of appending `struct fake_criterion_test`s by putting them into a section was buggy because extra padding was added between the elements in the section, so iterating through them from `__{start,stop}_fake_criterion_tests` didn't work correctly.
This new way uses `__attribute__((constructor))` to add each `struct fake_criterion_test` to a singly linked list. A singly linked list is used for simplicity, though it does mean the tests are run in reverse order within a file, but I don't really think the test order should matter, so this should be okay.
I also added the suite and test name to `struct fake_criterion_test` and print them out when running tests, which was helpful in distinguishing which tests were being run.
=> tests: replace `fake_criterion_tests` section with `__attribute__((constructor))`s adding to a linked list, fixing the padding bug

tools/rewriter/GenCallAsm.cpp
We previously observed the following:
```
Thread 2.1 received signal SIGSEGV, Segmentation fault
Memory tag violation while accessing address 0x00007ffff7f92028
Allocation tag 0x2
Logical tag 0x0.
[Switching to Thread 1089820.1089820]
0x00007ffff57d0a6c in __wrap_recurse_dso ()
from build-aarch64-compiler-rt/tests/recursion/librecursion_call_gates.so
(gdb) bt
#0  0x00007ffff57d0a6c in __wrap_recurse_dso ()
from build-aarch64-compiler-rt/tests/recursion/librecursion_call_gates.so
#1  0x00007ffff7f9f944 in recurse_main ()
#2  0x00007ffff7f9f964 in fake_criterion_recursion_main ()
#3  0x00007ffff7fa153c in main ()
(gdb) disassemble 
Dump of assembler code for function __wrap_recurse_dso:
0x00007ffff57d0a14 <+0>:	stp	x29, x30, [sp, #-16]!
0x00007ffff57d0a18 <+4>:	mov	x29, sp …
```
=> Tag accesses to stack pointer TLS locations in call gates

tools/rewriter/SourceRewriter.cpp
Make `RootDirectory` and `OutputDirectory` canonical paths immediately after reading CLI args.  #432 makes them absolute, but we need them to be fully canonical to reliably compare.
=> Canonicalize input paths in source rewriter

tests/post_condition/Output/dav1d.out, tests/post_condition/dav1d.c, tools/rewriter/GenCallAsm.cpp
This is done by pushing the param regs onto the stack in the prologue (if there's a post condition function), and then popping them before we call the post condition function.
Next we'll work on supporting more than the 6 param regs, as well as passing the return value.
=> rewriter: support the 6 x86 param regs for post condition functions

misc/test_runner/test_runner.c
I did this while debugging some tests regarding exit codes, signals, etc.  Not too important but pretty trivial.
=> test_runner: print expected exit code for tests

tools/rewriter/SourceRewriter.cpp
In `meson`, `*.S` asm files are pre-processed with the C preprocessor, and thus C flags are used to compile `*.S` asm files (unlike `*.s` asm files). To fix this on the `meson` side, we'd have to manually add args to each target instead of using `add_project_arguments(args, language: 'c')`, so this way is simpler.
=> rewriter: wrap callgate header in `#ifndef __ASSEMBLER__` so it doesn't get interpreted as asm

.github/workflows/ci.yml
There are errors about not finding `glib-2.0`; hopefully this fixes it.
=> ci: add `ligglib2.0-dev` to `aarch64-wip-test`

misc/test_runner/test_runner.c
This just makes the tests a bit easier to debug, as they match the naturally expected source order.
=> test_runner: un-reverse tests, as the `__attribute__((constructor))`s reverse them, too

.github/workflows/ci.yml
The persistent weird failures we're seeing in CI couldn't reproduce locally because I was doing an optimized build locally. We should test both configurations in CI, but for now let's get CI green by always testing optimized builds.
=> Always test optimized builds on AArch64

tests/CMakeLists.txt
We'll re-enable them in the PRs that fix them.
=> tests: disable failing tests on AArch64

.github/workflows/ci.yml
Seeing if this is relevant for the `simple1` test that's failing intermittently in CI.
EDIT: No, this fixes `three_keys_minimal`.
=> ci: use tweaked x18 tagging logic

runtime/libia2/include/permissive_mode.h, runtime/libia2/include/scrub_registers.h, runtime/tracer/get_inferior_pkru.h, runtime/tracer/track_memory_map.h, tests/macro_attr/include/functions.h, tests/three_keys_minimal/include/lib.h, tools/rewriter/TypeOps.h
A bunch of headers are missing include guards (which are mostly `#pragma once`s), so this adds them.  I ran into this with `tools/rewriter/TypeOps.h` but there are more headers missing so this fixes them all.
=> add `#pragma once` to headers w/ no include guards

tests/CMakeLists.txt, tests/type_confusion/CMakeLists.txt, tests/type_confusion/dav1d.c, tests/type_confusion/include/dav1d.h, tests/type_confusion/main.c
This is for the type confusion detection API we'll be adding as a potential pre/post-condition check.  This is the basic test for it before implementing the detection.
=> tests: add a `type_confusion` test w/ type confusion detection stubbed out

runtime/type-registry/Cargo.toml, runtime/type-registry/src/lib.rs
This switches the type registry to use the same type (`u32`) for `TypeId`s as the rewriter, and also adds some debug logs.  Also, updates to edition 2024.
=> runtime/type-registry: some small fixes/updates

runtime/type-registry/src/lib.rs
Now it will panic like this:
```shell
❯ RUST_BACKTRACE=1 ./build/x86_64/tests/type_confusion/type_confusion
protecting library: libtype_confusion_lib.so
Shared range 0: 0x7e3b26e6a000-0x7e3b26e6a000
Segment 3: 0x7e3b26e68000-0x7e3b26e6b000
Shared range 0 overlaps end of segment 3, adjusting end to 0x7e3b26e6a000
Shared range 1 overlaps start of segment 3, adjusting start to 0x7e3b26e69000
ia2_mprotect_with_tag(addr=0x7e3b26e69000, len=4096, prot=3, tag=2)
ia2_mprotect_with_tag(addr=0x7e3b26e6a000, len=4096, prot=3, tag=2)
ia2_mprotect_with_tag(addr=0x7e3b25e00000, len=4194304, prot=3, tag=2)
ia2_mprotect_with_tag(addr=0x7e3b26cc2000, len=4096, prot=3, tag=2)
ia2_mprotect_with_tag(addr=0x7e3b25a00000, len=4194304, prot=3, tag=1)
ia2_mprotect_with_tag(addr=0x7e3b26cc5000, len=4096, prot=3, …
```
=> runtime/type-registry: add more descriptive panic messages

runtime/libia2/include/ia2_internal.h
this will crash anyways and an abort is more explicit
=> runtime: ia2_stackptr_for_pkru should abort on invalid PKRU

tests/CMakeLists.txt, tools/rewriter/GenCallAsm.cpp
It turns out we were not aligning our stacks properly in ARM call gates since 13c495ddec8658101c2453362e76eba50518e1c3.
=> Fix structs test on ARM

runtime/libia2/include/ia2_compartment_init.inc, runtime/libia2/include/ia2_internal.h, runtime/libia2/include/permissive_mode.h
Developed working on FF compartmentalization. We don't handle C++ constructs crossing the compartment boundary but might need to include our headers from C++ sources.
=> libia2 fixes for C++ compat

.github/workflows/ci.yml, .gitmodules, CMakeLists.txt, benchmarks/CMakeLists.txt, benchmarks/microbench/CMakeLists.txt, benchmarks/microbench/microbench_indirect.c, benchmarks/microbench/microbench_lib.c, benchmarks/microbench/microbench_lib.h, benchmarks/microbench/microbench_lib2.h, benchmarks/microbench/microbench_lib_indirect.c, benchmarks/microbench/microbench_lib_indirect_compartment2.c, benchmarks/microbench/microbench_main.c, examples/video_player/CMakeLists.txt, examples/video_player/benchmark/CMakeLists.txt, examples/video_player/benchmark/benchmark.c, examples/video_player/benchmark/include/video_decoder.h, examples/video_player/benchmark/video_decoder.c, runtime/libia2/include/ia2.h
@rinon wrote some nice microbenchmarks and a larger video-decoding macrobenchmark. There's no reason not to merge these to keep them from bitrotting. This PR brings them into the build but doesn't run benchmarks as part of CI; we can decide if we want to do that later.
=> Forward-port benchmarks

runtime/libia2/include/ia2_internal.h
It seems that the pixel's kernel sets `SCTLR_EL1.SA0` (unconditionally?) so stack accesses at EL0 must be aligned to 16 bytes. This fixes a few accesses in our handwritten asm to enable running the minimal test on MTE-enabled hardware. There are likely some stack accesses in the callgates that also need to be fixed and I'd like to fix the TODO in `allocate_stack` before merging this (@fw-immunant any ideas there?). I checked that when the minimal test binary is run from a tmpfs MTE protection for its writeable file-backed mappings are enforced (see #469).
=> ARM: Align stack pointer to support SCTLR_EL1.SA0

.github/workflows/ci.yml, runtime/libia2/include/permissive_mode.h
We've been seeing some CI jobs take hours when they should take less than a minute. This should at least let these time out and not hose the whole infrastructure.
=> Add test timeout to CI

runtime/libia2/threads.c
I believe this is something clang-19 is stricter about than previous versions.
=> threads: fix signature of pthread_create

misc/test_runner/include/ia2_test_runner.h, misc/test_runner/test_runner.c, tests/post_condition/main.c
This reworks the test runner to be more rigourous in checking signals and exit codes.
For one, either `.signal` xor `.exit_code` should be set to non-zero, and setting both is now an error.
The error messages are clearer and more consistent now, too, as is the logic.
=> test_runner: ensure no signal with an expected signal is an error

runtime/libia2/include/ia2.h, tests/post_condition/dav1d.c, tools/rewriter/GenCallAsm.cpp, tools/rewriter/GenCallAsm.h, tools/rewriter/SourceRewriter.cpp
This is much more robust and flexible and is much closer to the end state for how this API will look.  It also makes the tests much simpler by encoding the options in the source code to be detected, rather than needing to specify them in the CLI or hardcoded like before.
Will the full gamut of the attribute API is implemented here, we still only support a single post-condition function, and no pre-condition functions yet.  Those will come next.
I also tested this more thoroughly in another branch with mostly complete multiple pre- and post-condition functions, but that implementation is more complex, so I wanted to put this in a separate PR.
=> rewriter: switch from hardcoded `--enable-dav1d_get_picture-post-condition` to `IA2_{PRE,POST}_CONDITION()` attribute annotation macros

tools/rewriter/CAbi.h, tools/rewriter/DetermineAbi.cpp, tools/rewriter/DetermineAbi.h, tools/rewriter/GenCallAsm.cpp, tools/rewriter/GenCallAsm.h, tools/rewriter/SourceRewriter.cpp
This wraps `AbiSignature` in a more generic `FnSignature` that also contains API info as well as the existing ABI info.  The API info is stored in `ApiSignature`, which contains `Param`s for the args and return.  Each `Param` contains the parameter name (if a parameter), the type name, the canonical type name, and a type ID based on the canonical name.  For now, the type ID is counted by interning the canonical types, so it's unique within a single `ia2-rewriter` invocation.
Next, we can use this API info to both define C functions (if we want to) and call into the `type-registry` library (#493) with type IDs for the arguments and return type.
=> rewriter: wrap `AbiSignature` in `FnSignature` that also stores API info (arg/return types)

tests/pre_post_condition/main.c, tests/pre_post_condition/src.c, tools/rewriter/GenCallAsm.cpp
It's simpler to do this initially in asm instead of splitting out the generated C pre- and post-condition functions (one each).
=> rewriter: implement multiple pre- and post-conditions in asm

.github/workflows/ci.yml
* Fixes #565.
This is the same ultimate `rustup toolchain install` command that `actions-rust-lang/setup-rust-toolchain@v1` uses, but that action is much slower (~70 s vs. ~17 s previously for the whole workflow), so we just run the main `rustup toolchain install` command directly.
I fixed #565 (likely) by `rm -rf ~/.rustup` in a temporary CI step, but this also adds `--profile minimal --no-self-update --allow-downgrade`, which should hopefully help with not running into situations like #565 again.
=> ci: use more specific `rustup toolchain install` command

runtime/libia2/ia2.c, runtime/libia2/include/ia2_threads.h, runtime/libia2/include/permissive_mode.h, runtime/libia2/init.c, runtime/libia2/threads.c, tests/permissive_mode/permissive_mode.c
* Fixes #405.
<details>
<summary>An example <code>mpk_log_*</code>:</summary>
```
start addr-end addr     perms offset  path
1987fffff000-198c00000000 ---p 00000000
3a0c00000000-3a1000000000 ---p 00000000
3efe50000000-3efe50001000 ---p 00000000
3efe50001000-3efe50002000 rw-p 00000000
3efe50002000-3efe50004000 ---p 00000000
3efe50004000-3efe50008000 rw-p 00000000
3efe50008000-3efe60000000 ---p 00000000
5ea323a3f000-5ea323a49000 r--p 00000000 /home/kkysen/work/rust/ia2/build/x86_64/tests/permissive_mode/permissive_mode
5ea323a49000-5ea323a7e000 r-xp 0000a000 /home/kkysen/work/rust/ia2/build/x86_64/tests/permissive_mode/permissive_mode
5ea323a7e000-5ea323a93000 r--p 0003f000 /home/kkysen/work/rust/ia2/build/x86_64/tests/permissive_mode/permissive_mode
5ea323a94000-5ea323a95000 r--p 00054000 …
```
=> permissive_mode: label stacks and TLS regions in all threads

runtime/libia2/include/ia2_threads.h, runtime/libia2/include/permissive_mode.h, runtime/libia2/threads.c, tests/permissive_mode/permissive_mode.c
* Part of #567.
<details>
<summary>An example <code>mpk_log_*</code>:</summary>
```
start addr-end addr     perms offset  path
17bfffff000-18000000000 ---p 00000000
2b23c0000000-2b23c0001000 ---p 00000000 [heap:compartment 1]
2b23c0001000-2b23c0002000 rw-p 00000000
2b23c0002000-2b23c0004000 ---p 00000000
2b23c0004000-2b23c0008000 rw-p 00000000
2b23c0008000-2b23d0000000 ---p 00000000
35f000000000-35f400000000 ---p 00000000
61b8588ee000-61b8588f8000 r--p 00000000 /home/kkysen/work/rust/ia2/build/x86_64/tests/permissive_mode/permissive_mode
61b8588f8000-61b85892d000 r-xp 0000a000 /home/kkysen/work/rust/ia2/build/x86_64/tests/permissive_mode/permissive_mode
61b85892d000-61b858942000 r--p 0003f000 /home/kkysen/work/rust/ia2/build/x86_64/tests/permissive_mode/permissive_mode …
```
=> permissive_mode: print thread name if there is one (in addition to tid)

runtime/libia2/ia2.c, runtime/libia2/include/ia2_threads.h, runtime/libia2/init.c, runtime/libia2/threads.c
=> permissive_mode: only store shared addrs in `IA2_DEBUG_LOG` mode and warn about using them as ptrs

.github/workflows/ci.yml, docs/compartmentalizing_dav1d.md, runtime/libia2/CMakeLists.txt, runtime/libia2/ia2.c, runtime/libia2/include/ia2_internal.h, runtime/libia2/init.c, runtime/libia2/memory_maps.c, runtime/libia2/memory_maps.h, tests/pre_post_condition/src.c
* Fixes #572.
`IA2_VERBOSE` and `IA2_DEBUG_MEMORY` and more precise and descriptive names, and it can be useful to enable one but not the other.
We also don't test with either of them on (previously `IA2_DEBUG_LOG`) in CI, so this enables that.  To avoid exponentially increasing CI times (because the self-hosted runner runs jobs sequentially), this only tests with them on rather than off, too.
=> libia2: split `IA2_DEBUG_LOG` into `IA2_VERBOSE` and `IA2_DEBUG_MEMORY`

runtime/libia2/include/ia2_internal.h, runtime/libia2/memory_maps.c
* Fixes #571.
`IA2_MAX_THREADS` was once used as part of a different design of per-compartment stacks, but we never actually used that non-TLS design, so there is no limit to the number of threads.  However, the memory maps code uses it now, so this just moves it there.  Thus, it's no longer public in `ia2_internal.h` and behind `IA2_DEBUG_MEMORY` in a `*.c` file.
~~Unlike what #571 and https://github.com/immunant/IA2-Phase2/pull/557#discussion_r2095889891 say, this doesn't actually rename it.  I didn't really see a reason to do so now that it's clearly behind `IA2_DEBUG_MEMORY` and in `memory_maps.c`, so it's not visible outside that file.~~
It's renamed to just `MAX_THREADS` now.  It's not a public export anymore so it doesn't need the `IA2_*` prefix anymore.
=> libia2/memory_maps: make `IA2_MAX_THREADS` private and move it to `memory_maps.c` behind `IA2_DEBUG_MEMORY`

runtime/libia2/memory_maps.c
Fixes https://github.com/immunant/IA2-Phase2/pull/555/files#r2102990872.
=> libia2/memory_maps: handle `sscanf` failure

runtime/libia2/CMakeLists.txt
We use `__real_free` in `memory_maps.c`, so we need this now.
=> libia2: add `-Wl,--wrap=free` for when we link `libia2` but not the `partition-alloc` shim

runtime/libia2/memory_maps.c, runtime/libia2/memory_maps.h, runtime/libia2/threads.c
* Fixes #567.
<details>
<summary>An example <code>mpk_log_*</code>:</summary>
```
start addr-end addr     perms offset  path
176260000000-176260001000 ---p 00000000 [heap:compartment 1]
176260001000-176260002000 rw-p 00000000
176260002000-176260004000 ---p 00000000
176260004000-176260008000 rw-p 00000000
176260008000-176270000000 ---p 00000000
200bfffff000-201000000000 ---p 00000000
3c1c00000000-3c2000000000 ---p 00000000
5f22d9d50000-5f22d9d5a000 r--p 00000000 /home/kkysen/work/rust/ia2/build/x86_64/tests/permissive_mode/permissive_mode
5f22d9d5a000-5f22d9d8f000 r-xp 0000a000 /home/kkysen/work/rust/ia2/build/x86_64/tests/permissive_mode/permissive_mode
5f22d9d8f000-5f22d9da4000 r--p 0003f000 /home/kkysen/work/rust/ia2/build/x86_64/tests/permissive_mode/permissive_mode …
```
=> libia2/memory_maps: label start fn

runtime/libia2/ia2.c, runtime/libia2/include/ia2_internal.h
This simplifies most uses of IA2_VERBOSE to make logging easier and more uniform. This commit intentionally ignores the existing use of IA2_VERBOSE in ia2_internal.h since (ideally) the static function defined in that header should be move to a source file at some point.
=> runtime/libia2: Simplify use of IA2_VERBOSE

.github/workflows/ci.yml, CMakeLists.txt, runtime/CMakeLists.txt, runtime/libia2/CMakeLists.txt, runtime/partition-alloc/CMakeLists.txt, runtime/tracer/CMakeLists.txt, runtime/type-registry/CMakeLists.txt, tools/CMakeLists.txt, tools/pad-tls/CMakeLists.txt, tools/rewriter/CMakeLists.txt
cmake 4.0 fixes a lot of issues where `ia2-sandbox` would get stuck, including in #582, where we're unsure how else to fix the issue, but where cmake 4.0 does fix the issue.
=> ci: update to cmake 4

tests/CMakeLists.txt, tests/memory_maps/2.c, tests/memory_maps/3.c, tests/memory_maps/4.c, tests/memory_maps/CMakeLists.txt, tests/memory_maps/main.c
This differs from the existing permissive mode test in that it just prints the labeled memory maps to `stdout` instead of saving them to a log file. This is more convenient during testing.
It also tests more compartments.
=> tests/memory_maps: add a memory maps test with multiple compartments and threads

tests/type_confusion/dav1d.c, tests/type_confusion/include/dav1d.h, tests/type_confusion/main.c
`donna` is down, so I'm testing this in CI.
@fw-immunant, is this what you meant?
=> tests/type_confusion: add `dav1d_{alloc,free}` instead of `IA2_SHARED_DATA` and make `Dav1dContext` opaque

runtime/type-registry/src/lib.rs
* Fixes #603.
I still want to add `cargo test` to `ninja check`, but that's been tricky, so let me just fix this first.
=> type-registry: `#[cfg(not(test))]` for `no_std` code so we can run `cargo test`

runtime/type-registry/Cargo.lock, runtime/type-registry/Cargo.toml, runtime/type-registry/src/lib.rs
This fixes some things in the `no_std` implementation of the `type-registry`, specifically:
* We use `libc` functions from the `libc` crate instead of declaring them ourselves (sometimes slightly wrong).
* We use `spin::RwLock` instead of rolling our own spin-based `Mutex`, which hasn't been checked for correctness, and is less ideal than a `RwLock`, which it originally was.
* ~~We use `hashbrown::HashMap` instead of `alloc::collections::BTreeMap`.  We would normally use `std::collections::HashMap`, but it hasn't yet been moved to `alloc`, and it internally uses `hashbrown` anyways.  Moreover, we use `fnv` as the hasher, as that's `const fn` compatible.~~
* Some other little cleanups.
=> type-registry: some `no_std` improvements/fixes

tests/CMakeLists.txt, tests/terminating_threads/CMakeLists.txt, tests/terminating_threads/lib.c, tests/terminating_threads/main.c
This tests various combinations of threads terminating, including a matrix of:
* 1, 2, and 11 threads (including the main thread)
* threads terminating by `return`, `exit(0)`, `abort()`, `pthread_exit(0)` (including the main thread) or `pause()`ing or `sleep`ing
* threads being `pthread_join`ed, `pthread_cancel`ed, or through process termination
However, `abort()` currently incurs a ~1 second penalty for some reason, so that's disabled. Moreover, `pthread_exit` causes `SIGILL` and `pthread_cancel` causes `SIGSEGV`, so these are disabled, too.
Furthermore, just like the other existing thread tests (`threads` and `protected_threads`), `terminating_threads` runs `WITHOUT_SANDBOX`, as the tracer fails on all of them.
I'll add tests covering `atexit`, `pthread_cleanup_push`, …
=> tests/terminating_threads: add a test for various combinations of ways threads can terminate

.github/workflows/ci.yml
Not sure why this was working before, but it's not anymore and it doesn't look like it should've at any point.  The `packages` string is space-delimited, not a list, so we can't put inline comments (annoyingly).
=> ci: don't use `#` comments inside a YAML string

runtime/libia2/init.c
The tagged stack is what should be used for accesses, but the `mmap`ped untagged stack ptr is what will show up in memory maps.
=> libia2: save stack ptr before tagging it on arm

tests/terminating_threads/main.c
`exit` does cleanups, so it may have some issues that may be causing some of the CI heisenbugs.  `#if 0` these tests out seems to help CI avoid errors now.  Note that `_exit` was still causing errors.
=> tests/terminating_threads: `#if 0` out broken tests instead of using `exit(0)`, which has bugs itself

runtime/libia2/CMakeLists.txt, runtime/libia2/include/ia2_internal.h, runtime/libia2/init.c, runtime/libia2/memory_maps.c, runtime/libia2/thread_name.c, runtime/libia2/thread_name.h
* Fixes #546.
I did this with `pthread_key_create` and `pthread_setspecific`, as this makes the implementation very simple and should handle all ways thread terminate (`return`, `pthread_exit`, `pthread_cancel`).
`pthread_key_create` creates a TLS key with a destructor function that's called whenever a thread terminates (however that happens).  This is used to `munmap` all the thread stacks.  Since multiple stacks are used per thread and `pthread_key_create` can only store a single ptr as its data, the thread stacks are stored in a separate `__thread` TLS array and `pthread_setspecific` is used to simply store a non-`NULL` value as the data so that the destructor will eventually be run.
=> libia2: free compartment stacks on thread termination

misc/test_runner/include/ia2_test_runner.h, tests/terminating_threads/main.c
This uses `mincore` to test that thread stacks are freed upon thread termination.  Note that this only checks that compartment 1 (`main.c`)'s stacks are freed.
=> tests/terminating_threads: test that stacks are freed upon thread termination

tools/rewriter/SourceRewriter.cpp
This was causing `ninja all` to segfault locally.
=> rewriter: fix segfault from iterator invalidation

runtime/libia2/ia2.c, runtime/libia2/init.c, runtime/libia2/memory_maps.c, runtime/libia2/memory_maps.h, runtime/libia2/threads.c
This cherry-picks the little improvements from #619 and #585 since we're not going to merge #619 and instead make `liblibia2.a` a `.so`.  This leaves out the larger lock-free change from #585 that I think was causing the multiple definitions error (though I'll see in CI).  I also made more functions `static` where possible so `libia` isn't exporting symbols it doesn't have to.
=> memory_maps: various improvements from #619, #585

external/chromium/src/base/allocator/partition_allocator/partition_address_space.h, runtime/partition-alloc/README.md
This was something I encountered when working on Firefox. With our changes to partition-alloc, all of our allocations go through their thread-isolated address pools, which only have 256 MB of address space, causing OOM issues when running Firefox. Since we only use the thread-isolated pools, I think giving them the max pool size is reasonable.
=> Increase the size of the thread-isolated address pools

runtime/partition-alloc/include/ia2_allocator.h
In the Firefox demo I ran into the issue that the shared allocation functions were showing up as undefined hidden symbols, causing linker errors:
```
0:06.53 ld.lld: error: undefined hidden symbol: shared_strdup
```
I think this is fixed by adding the `visibility("default")` attribute in the headers (or at least that's how we solved similar symbol visibility issues that we ran into on ff). In `shared_allocator.cc`, where these functions are defined, we're using `SHIM_ALWAYS_EXPORT` to mark visibility, but we're not using that define when declaring these functions `ia2_allocator.h`. In theory we'd just want to add `SHIM_ALWAYS_EXPORT` to the header, however it comes from a header in partition-alloc that we probably don't want to expose as part of the public API of IA2 (e.g. because we …
=> Mark shared allocation functions with visibility("default") in header
