immunant/IA2-Phase2

header-rewriter/HeaderRewriter.cpp
After we removed the .symver wrapper, some headers
stopped being inserted properly. This change moves
the header logic into a pass that always runs.
=> Move header #include generation into the FnPtrPrinter pass

header-rewriter/DetermineAbi.cpp
Updated my machine and ran into an API change.
=> Fix build with Clang 15

.clang-format, header-rewriter/GenCallAsm.cpp, libia2/include/ia2.h, partition-alloc/CMakeLists.txt
Shouldn't be contentious, will merge if CI passes.
=> various minor cleanups

header-rewriter/GenCallAsm.cpp
This fixes backtraces in gdb. Closes #189.
Note that since call gate wrappers switch stacks they effectively have one frame on each stack. Since we already have to save rbp on the caller's stack, this sets that stack as the frame pointer. Running a few tests in gdb with `watch ia2_stackptrs` showed correct backtraces, but other tools may require creating two frames per call gate if they require rsp and rbp to point to the same stack for whatever reason.
=> Handle frame pointer in code generated for call gate wrappers

header-rewriter/tests/CMakeLists.txt, header-rewriter/tests/recursion/CMakeLists.txt, header-rewriter/tests/recursion/Output/recursion.insecure.out, header-rewriter/tests/recursion/Output/recursion.out, header-rewriter/tests/recursion/dso.c, header-rewriter/tests/recursion/include/dso/recursion_dso.h, header-rewriter/tests/recursion/include/main/recursion_main.h, header-rewriter/tests/recursion/main.c
Adds a test that makes mutually recursive calls between two compartments.
=> Add a recursive call test

header-rewriter/SourceRewriter.cpp, header-rewriter/tests/read_config/builtin.c, header-rewriter/tests/read_config/plugin.c, header-rewriter/tests/simple1/main.c, header-rewriter/tests/trusted_indirect/main.c
=> Add used attribute on static functions that have their address taken

header-rewriter/tests/lit.cfg.py, header-rewriter/tests/threads/include/library.h, header-rewriter/tests/threads/library.c, header-rewriter/tests/threads/main.c
This test just needed its lit invocations updated. Could someone double-check that I've done it right?
=> tests/threads: re-enable test

cmake/define-ia2-wrapper.cmake, cmake/define-test.cmake
=> cmake: avoid re-running test build steps

libia2/ia2.c, rewriter/tests/threads/main.c
Shouldn't be anything contentious.
=> Fix a few warnings

rewriter/tests/read_config/CMakeLists.txt, rewriter/tests/read_config/Output/read_config.insecure.out, rewriter/tests/read_config/Output/read_config.out, rewriter/tests/read_config/main.c, rewriter/tests/read_config/plugin.c
I'm curious if this works in CI.
=> rewriter: tests: run read_config in its test

libia2/include/ia2.h, rewriter/tests/threads/library.c, rewriter/tests/threads/main.c, rewriter/tests/tls_protected/main.c
Shouldn't be contentious, so I'll merge when CI passes.
=> tests: use `ia2_get_pkru`

libia2/include/permissive_mode.h
Adds more state to the MPK error log.
=> Improve permissive mode with additional context

libia2/include/ia2.h
This cleans things up a lot. We need a different base case because we often treat compartment 0 specially.
=> ia2.h: simplify with REPEATB(n, fn, basefn) macro

.github/workflows/ci.yml
- Save artifacts on test failure
- Update checkout action
=> Minor CI improvements

CMakeLists.txt, cmake/define-ia2-wrapper.cmake, cmake/define-test.cmake, examples/CMakeLists.txt, examples/video_player/CMakeLists.txt, examples/video_player/include/video_decoder.h, examples/video_player/video_decoder.c, examples/video_player/video_player.c
Port the video player example from Phase 1
written in Rust to C.
=> examples/video_player: Add video player

rewriter/SourceRewriter.cpp
We want these failure exits irrespective of debug/release mode.
=> rewriter: use abort() for unconditional failure exits

runtime/track_memory_map.c
A couple things here were technically wrong but I think this doesn't actually change behavior any.
=> Minor fixes to memory-map event update

libia2/include/ia2_compartment_init.inc
=> compartment init: fix spurious UBSan error

docs/usage.md, tests/lit.cfg.py
=> Fix references to `libia2/include` directory

tests/structs/include/structs.h, tests/structs/main.c, tests/structs/structs.c
=> Improve coverage of structs test

tools/rewriter/SourceRewriter.cpp
Split out of lib-mode work so we can merge them eagerly. Most commits are semantics preserving, a few are bug fixes.
=> Rewriter cleanups

misc/spoofed_criterion/include/criterion/new/assert.h, runtime/libia2/exit.c, runtime/libia2/ia2.c, runtime/libia2/include/ia2_compartment_init.inc, runtime/libia2/include/ia2_internal.h, runtime/libia2/include/test_fault_handler.h, runtime/libia2/main.c
Still need to figure out x18 handling and check the ARM64 ABI spec for stack alignment requirements.
=> runtime/libia2: Implement __wrap_main, exit and allocate thread-local stacks

tools/rewriter/SourceRewriter.cpp
This doesn't change any behavior but does make it easier to poke at the rewriter in gdb. I'll merge this as long as CI passes.
=> tools/rewriter: access globals directly, not through `llvm::cl::opt<T>`

misc/spoofed_criterion/include/criterion/criterion.h, misc/spoofed_criterion/test_runner.c
=> misc/spoofed_criterion: Fork for tests on ARM

.github/workflows/ci.yml, cmake/aarch64-toolchain.cmake
~This also includes a bunch of work to make more stuff compile, which I'll probably separate from this branch before merging.~ Done.
What a CI battle. We won in the end.
=> Use clang fork for ARM CI

tools/rewriter/SourceRewriter.cpp
This fixes #408, as `libclangTooling` handles relative paths so poorly. This moves the logic into the `DirectoryParser`, which centralizes it a bit more, and ensures there's no non-absolute path created before we start using it.
* Fixes #408.
=> rewriter: immediately make directory CLI args absolute

runtime/libia2/include/permissive_mode.h
Short-lived programs (like our tests) running in permissive mode may not show all MPK violations in the logs if the logging thread tries to exit while `mpk_err`s are still queued for logging. This flushes the queue before `exiting` to get all errors in the logs. @rinon I split this out from the bigger permissive mode improvements in #421 and just wanted a quick look to double check my logic here. Also this doesn't work for tests using criterion since it installs its own signal handler so I just tested by adding a compartment violation to `minimal_no_criterion`.
=> runtime: Flush queue before exiting process in permissive mode

docs/usage.md
These docs reflect all the steps I needed to get the rewriter working for zlib. Let me know if anything seems wrong, I tried to test everything but I may not have captured all the edge cases for the rewriter.
* Closes #409.
=> Add documentation for the rewriter

runtime/libia2/include/ia2.h, runtime/libia2/include/ia2_internal.h, tests/abi/include/abi.h, tests/abi/main.c, tests/read_config/main.c, tests/rewrite_fn_ptr_eq/main.c, tests/rewrite_macros/include/lib.h, tests/rewrite_macros/main.c, tests/simple1/main.c, tests/trusted_indirect/main.c, tools/rewriter/GenCallAsm.cpp, tools/rewriter/GenCallAsm.h, tools/rewriter/SourceRewriter.cpp
This PR just rebases what should've been merged to main in #436 and fixes a few conflicts introduced by #435.
=> Pass indirect call target in first register v2

.github/workflows/ci.yml
Sadly I think the CI run for this will likely not populate the cache because it's a PR, but there might be enough output to see if this fixes the problem.
=> ci: attempt to fix rtlib caching

misc/test_runner/test_runner.c
This is handy for debugging some subtler interactions of our test runner and process state.
=> Add means to run one test without forking

tests/post_condition/CMakeLists.txt, tests/post_condition/Output/dav1d.out, tests/post_condition/dav1d.c, tests/post_condition/include/dav1d.h, tests/post_condition/main.c
Now we actually test that an `assert` (for now an `exit`) post condition works.
=> tests: split `post_condition` `main` test into `normal` and `corrupt_bounds` tests to have a control

cmake/ia2.cmake, runtime/libia2/CMakeLists.txt
This silences some warnings and speeds up incremental builds a bit.
=> Handful of CMake fixes

CMakeLists.txt, cmake/define-test.cmake, cmake/ia2.cmake, cmake/qemu-command.cmake
This improves incremental builds some and factors out logic for running QEMU, which we want for supporting benchmarks on ARM.
=> CMake cleanups

external/chromium/src/base/allocator/partition_allocator/page_allocator_internals_posix.h, external/chromium/src/base/allocator/partition_allocator/thread_isolation/thread_isolation.cc, runtime/libia2/init.c, tests/CMakeLists.txt
~Needs some cleanup and still debugging structs test.~
=> Support shared heap allocations on ARM

runtime/libia2/include/ia2.h, runtime/libia2/include/permissive_mode.h, runtime/libia2/init.c
* Part of #405.
* Split out from #421.
=> permissive_mode: label (main thread) ia2 stacks

runtime/libia2/ia2.c, runtime/libia2/include/permissive_mode.h
* Part of #405.
* Split out from #421.
=> permissive_mode: label the (main thread) TLS regions

external/chromium/src/base/allocator/partition_allocator/partition_address_space.cc, runtime/libia2/include/permissive_mode.h, tests/permissive_mode/permissive_mode.c
=> permissive_mode: label partition-alloc heaps

tests/pre_post_condition/include/src.h, tests/pre_post_condition/main.c, tests/pre_post_condition/src.c
Fixes https://github.com/immunant/IA2-Phase2/pull/511#discussion_r2079684166.
=> tests/pre_post_condition: add tests with fns with odd numbers of args
